### ISSUE TITLE
Technical Analysis

### ISSUE THREAD

**Issue by BjarkeKarlsen** [MartinStokholm/PRJ4_Repo#22]

**Comment by BjarkeKarlsen** [comment]
An analysis of the pros and cons of some of the possible technologies that we could use to build our project. Fx
Front-end (React vs WPF)
Back-end (API vs Razor Pages, NoSQL vs SQL, etc)

**Comment by gsglintborg** [comment]
The technical analysis is done.
Please review and comment if anything needs to be added or deleted
